name: Django CI with MySQL and SQLAlchemy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        echo "mysqlclient>=2.1.0" > requirements.txt
        echo "sqlalchemy>=1.4.0" >> requirements.txt
        pip install -r requirements.txt

    - name: Set Environment Variables
      run: |
        echo "DATABASE_URL=mysql://root:${{ secrets.MYSQL_ROOT_PASSWORD }}@localhost:3306/CFTdatabase" >> .env

    - name: Debugging
      run: |
        pwd
        ls -la

    - name: Changing Directory
      run: |
        cd csye6225
        ls -la

    - name: Run Django Migrations
      run: python manage.py migrate

    - name: Run Django Tests
      run: python manage.py test

    - name: Cleanup MySQL Container
      run: docker stop mysql
