name: Django CI with SQLAlchemy and MySQL

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8] # Choose the Python version you're using

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up MySQL
      uses: mysql/setup-mysql@v1
      with:
        mysql-version: '5.7'
        server-id: '1'
        mysql-port: '3306'
        mysql-root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        mysql-databases: 'CFTdatabase'

    # Add the mysql/setup-mysql action below:
    - name: Set up MySQL with mysql/setup-mysql
      uses: mysql/setup-mysql@v2
      with:
        mysql-version: '5.7'
        mysql-server-port: 3306
        mysql-root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        mysql-databases: 'CFTdatabase'
        
    - name: Apply Django Migrations
      run: python manage.py migrate

    - name: Set Environment Variables (use GitHub Secrets)
      run: |
        echo "DATABASE_URL=mysql://root:${{ secrets.MYSQL_ROOT_PASSWORD }}@localhost:3306/root" >> .env

    - name: Run Integration Tests
      run: python manage.py test

    - name: Cleanup MySQL
      run: |
        mysql -h localhost -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "DROP DATABASE CFTdatabase;"
