name: Django CI with MySQL and SQLAlchemy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install django  # Install Django inside the virtual environment

    - name: Install other dependencies
      run: |
        echo "mysqlclient>=2.1.0" > requirements.txt
        echo "sqlalchemy>=1.4.0" >> requirements.txt
        pip install -r requirements.txt

    - name: Set Environment Variables
      run: |
        echo "DATABASE_URL=mysql://root:${{ secrets.MYSQL_ROOT_PASSWORD }}@localhost:3306/CFTdatabase" >> .env

    - name: Debugging
      run: |
        pwd
        ls -la

    - name: Changing Directory
      run: |
        cd csye6225  # Change to the correct directory where manage.py is located
        ls -la  # List the contents of the directory to verify

    - name: Run Django Migrations
      run: |
        cd csye6225
        python manage.py migrate
        # Make sure to run other necessary commands related to your Django project here

    - name: Run Django Tests
      run: |
        python manage.py test
        # Run other tests or commands if needed

    - name: Cleanup MySQL Container
      run: docker stop mysql
