name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display directory structure
        run: tree /github/workspace

  job_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display directory structure
        run: tree /github/workspace
